"""
Django settings for Ati_smart_platform project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Personal data definition
# settings.py
ROLES = (
    ("CEO", "Chief Executive Officer"),
    ("HR_MANAGER", "HR Manager"),
    ("MANAGER", "Department Manager"),
    ("EMPLOYEE", "Employee"),
)

CEO_ROLES = (
    ("HR_MANAGER", "HR Manager"),
)

HR_ROLES = (
    ("MANAGER", "Department Manager"),
    ("EMPLOYEE", "Employee"),
)

DEPARTMENTS = (
    ("HR", "HR and Accounting"),
    ("Cybersecurity", "Cybersecurity"),
    ("Marketing", "Marketing and Sales"),
    ("Software", "Software Engineering"),
    ("Technical", "Technical Department"),
    ("Operations", "Operations Department"),
    ("Data", "Data Science"),
)

DEPARTMENT_JOBS = {
    "HR and Accounting": ["HR Specialist", "Accountant", "Payroll Manager"],
    "Cybersecurity": ["Security Analyst", "Penetration Tester"],
    "Marketing and Sales": ["Sales Manager", "Marketing Specialist"],
    "Software Engineering": ["Software Engineer", "DevOps Engineer"],
    "Technical Department": ["Technical Support", "Field Engineer"],
    "Operations Department": ["Operations Manager", "Logistics Coordinator"],
    "Data Science": ["Data Scientist", "Data Analyst"],
}

AUTH_USER_MODEL = 'users.User'  # Add this to manage the model

# Define the COMPANY_NAME variable
COMPANY_NAME = "ATI Smart Platform"
# Define the COMPANY_EMAIL variable
COMPANY_EMAIL = "ibrahim.ati2024@gmail.com"

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
BASE_URL = "https://gmail.com"  # For email links
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'ibrahim.ati2024@gmail.com.com'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w17p)ujn_a8f4z=&s#9v%_o$6yt%=l*-fk4^ka&kr9-_(sg0gx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1  # Usually the first site has ID=1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'users',
    'bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ati_smart_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ati_smart_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add these to settings.py

# Authentication
# LOGIN_REDIRECT_URL = 'dashboard'  # Default after login
LOGOUT_REDIRECT_URL = 'login'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Media files (for profile pictures)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration (if using Gmail)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ibrahim.ati2024@gmail.com'
EMAIL_HOST_PASSWORD = 'AcheteIci2024#'  # Use App Password, not main password

# App version variable
VERSION = "1.00"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"