# """
# Django settings for Ati_smart_platform project.

# Generated by 'django-admin startproject' using Django 5.2.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Personal data definition
# # settings.py
# ROLES = (
#     ("CEO", "Chief Executive Officer"),
#     ("HR_MANAGER", "HR Manager"),
#     ("MANAGER", "Department Manager"),
#     ("EMPLOYEE", "Employee"),
# )

# CEO_ROLES = (
#     ("HR_MANAGER", "HR Manager"),
# )

# HR_ROLES = (
#     ("MANAGER", "Department Manager"),
#     ("EMPLOYEE", "Employee"),
# )

# DEPARTMENTS = (
#     ("HR", "HR and Accounting"),
#     ("Cybersecurity", "Cybersecurity"),
#     ("Marketing", "Marketing and Sales"),
#     ("Software", "Software Engineering"),
#     ("Technical", "Technical Department"),
#     ("Operations", "Operations Department"),
#     ("Data", "Data Science"),
# )

# DEPARTMENT_JOBS = {
#     "HR and Accounting": ["HR Specialist", "Accountant", "Payroll Manager"],
#     "Cybersecurity": ["Security Analyst", "Penetration Tester"],
#     "Marketing and Sales": ["Sales Manager", "Marketing Specialist"],
#     "Software Engineering": ["Software Engineer", "DevOps Engineer"],
#     "Technical Department": ["Technical Support", "Field Engineer"],
#     "Operations Department": ["Operations Manager", "Logistics Coordinator"],
#     "Data Science": ["Data Scientist", "Data Analyst"],
# }

# AUTH_USER_MODEL = 'users.User'  # Add this to manage the model

# # Define the COMPANY_NAME variable
# COMPANY_NAME = "ATI Smart Platform"
# # Define the COMPANY_EMAIL variable
# COMPANY_EMAIL = "ibrahim.ati2024@gmail.com"

# # SECURITY WARNING: keep the secret key used in production secret!
# # SECURITY WARNING: don't run with debug turned on in production!
# BASE_URL = "https://gmail.com"  # For email links
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL = 'ibrahim.ati2024@gmail.com.com'


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-w17p)ujn_a8f4z=&s#9v%_o$6yt%=l*-fk4^ka&kr9-_(sg0gx'

# # load data from a .env file if it exists
# try:
#     from dotenv import load_dotenv
#     load_dotenv(BASE_DIR / '.env')  # Load environment variables from .env file
# except ImportError:
#     print("Warning: dotenv module not found. Environment variables will not be loaded.")
# # If you have a .env file, you can set the SECRET_KEY there
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

# SITE_ID = 1  # Usually the first site has ID=1

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     # include media files
#     'django.contrib.staticfiles',
#     'django.contrib.sites',
#     'django.contrib.flatpages',
#     'django.contrib.humanize', # For human-readable dates, numbers, etc.
#     'django.contrib.sitemaps',  # For sitemap support
#     'users',
#     'bootstrap5',
#     'crispy_forms',
#     'crispy_bootstrap5',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'Ati_smart_platform.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'Ati_smart_platform.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # Add these to settings.py

# # Authentication
# # LOGIN_REDIRECT_URL = 'dashboard'  # Default after login
# LOGOUT_REDIRECT_URL = 'login'

# # Crispy Forms
# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"

# # Media files (for profile pictures)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'  # Directory to store uploaded files

# # Email Configuration (if using Gmail)
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'ibrahim.ati2024@gmail.com'
# EMAIL_HOST_PASSWORD = 'AcheteIci2024#'  # Use App Password, not main password

# # App version variable
# VERSION = "0.0.1"

# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"

"""
Django settings for Ati_smart_platform project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Ensure the root of the repository is available for static/media roots
# This assumes settings.py is in src/Ati_smart_platform/
REPO_ROOT = BASE_DIR.parent

# --- 1. Environment Variables Loading ---
# Load environment variables from .env file if it exists at the repository root
# This should be the first thing to run to ensure all env vars are available
try:
    load_dotenv(REPO_ROOT / '.env')
except ImportError:
    print("Warning: python-dotenv module not found. Environment variables will not be loaded.")
except Exception as e:
    print(f"Error loading .env file: {e}")


# --- 2. Core Django Settings ---
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-w17p)ujn_a8f4z=&s#9v%_o$6yt%=l*-fk4^ka&kr9-_(sg0gx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
if '' in ALLOWED_HOSTS:
    ALLOWED_HOSTS.remove('') # Remove empty string if split results in it

SITE_ID = 1 # Usually the first site has ID=1

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django.contrib.humanize', # For human-readable dates, numbers, etc.
    'django.contrib.sitemaps', # For sitemap support

    # Third-party apps
    'bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',

    # My apps
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ati_smart_platform.urls' # Corrected based on project name

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates', # Project-level templates (e.g., base.html)
        ],
        'APP_DIRS': True, # This allows Django to find templates in app-specific 'templates' directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Useful for debug mode
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context processors if needed
            ],
        },
    },
]

WSGI_APPLICATION = 'Ati_smart_platform.wsgi.application' # Corrected based on project name


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication
AUTH_USER_MODEL = 'users.User' # Add this to manage the model
# LOGIN_REDIRECT_URL = 'dashboard' # Default after login (uncomment and set your actual redirect URL)
LOGOUT_REDIRECT_URL = 'login' # Define your login URL if not using Django defaults


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- 3. Static and Media Files ---
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# Where Django will look for additional static files (e.g., project-wide static)
STATICFILES_DIRS = [
    REPO_ROOT / 'static', # For project-level static files (like logo, general images)
]

# The directory where `collectstatic` will gather all static files for deployment
STATIC_ROOT = REPO_ROOT / 'staticfiles' # New directory for collected static files


# Media files (for user-uploaded content like profile pictures, joined files)
MEDIA_URL = '/media/'
MEDIA_ROOT = REPO_ROOT / 'media' # Directory to store uploaded files


# --- 4. Email Configuration ---
# Email Configuration (if using Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'your_email@example.com') # Fallback for development
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'your_app_password') # Fallback for development
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000') # For email links, use a proper production URL


# --- 5. Custom & Third-Party App Settings ---
# Crispy Forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Personal data definitions (Roles, Departments, Company Info)
# It's generally good practice to keep these as Python constants if they are fixed.
# If these might change frequently or be dynamic, consider storing them in the database.
ROLES = (
    ("CEO", "Chief Executive Officer"),
    ("HR_MANAGER", "HR Manager"),
    ("MANAGER", "Department Manager"),
    ("EMPLOYEE", "Employee"),
)

CEO_ROLES = (
    ("HR_MANAGER", "HR Manager"),
)

HR_ROLES = (
    ("MANAGER", "Department Manager"),
    ("EMPLOYEE", "Employee"),
)

DEPARTMENTS = (
    ("HR", "HR and Accounting"),
    ("Cybersecurity", "Cybersecurity"),
    ("Marketing", "Marketing and Sales"),
    ("Software", "Software Engineering"),
    ("Technical", "Technical Department"),
    ("Operations", "Operations Department"),
    ("Data", "Data Science"),
)

DEPARTMENT_JOBS = {
    "HR and Accounting": ["HR Specialist", "Accountant", "Payroll Manager"],
    "Cybersecurity": ["Security Analyst", "Penetration Tester"],
    "Marketing and Sales": ["Sales Manager", "Marketing Specialist"],
    "Software Engineering": ["Software Engineer", "DevOps Engineer"],
    "Technical Department": ["Technical Support", "Field Engineer"],
    "Operations Department": ["Operations Manager", "Logistics Coordinator"],
    "Data Science": ["Data Scientist", "Data Analyst"],
}

COMPANY_NAME = "ATI Smart Platform"
COMPANY_EMAIL = "ibrahim.ati2024@gmail.com" # Consider moving to .env if this changes based on deployment


# App version variable
VERSION = "0.0.1"


# --- 6. Default Auto Field ---
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


if not DEBUG:
    # Security settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # Static files
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')