# Generated by Django 4.2.21 on 2025-05-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department', models.CharField(choices=[('HR', 'HR and Accounting'), ('Cybersecurity', 'Cybersecurity'), ('Marketing', 'Marketing and Sales'), ('Software', 'Software Engineering'), ('Technical', 'Technical Department'), ('Operations', 'Operations Department'), ('Data', 'Data Science')], max_length=255)),
                ('role', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('HR_MANAGER', 'HR Manager'), ('MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('employee_id', models.CharField(max_length=255, unique=True)),
                ('professional_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('personal_email', models.EmailField(max_length=254)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('personal_picture', models.FileField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_activated', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
