# Generated by Django 4.2.21 on 2025-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_files',
            field=models.FileField(blank=True, null=True, upload_to='joined_files/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
    ]
