# Generated by Django 4.2.21 on 2025-05-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_joined_files_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
    ]
