# Generated by Django 4.2.21 on 2025-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'HR and Accounting'), ('Cybersecurity', 'Cybersecurity'), ('Marketing', 'Marketing and Sales'), ('Software', 'Software Engineering'), ('Technical', 'Technical Department'), ('Operations', 'Operations Department'), ('Data', 'Data Science')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
