# Generated by Django 4.2.21 on 2025-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_department_alter_user_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_picture',
            field=models.FileField(blank=True, default='static/images/logo.png', null=True, upload_to='profile_pics/'),
        ),
    ]
